// Builds content/blog-topics.json — the master plan of ~540 article topics across
// the 10 clusters. Curated, hyper-specific, query-shaped titles (one query → one
// article). This script is the source of truth; re-run it to regenerate the JSON.
// It validates: every cluster slug is real, every slug is unique and <=60 chars,
// and no generated slug collides with a seed. It does NOT assign dates (see
// scripts/assign-publish-dates.mjs) and does NOT generate articles.
//
// Run: node scripts/build-topics.mjs

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { CLUSTER_SLUGS } from '../src/data/blogClusters.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, '..', 'content', 'blog-topics.json')

const STOP = new Set(['a', 'an', 'the', 'to', 'of', 'for', 'in', 'on', 'your',
  'with', 'how', 'what', 'is', 'do', 'does', 'when', 'why', 'from'])

function slugify(s) {
  let slug = s.toLowerCase()
    .replace(/\.js\b/g, 'js')          // next.js -> nextjs, vue.js -> vuejs
    .replace(/\ba\/b\b/g, 'ab')        // "A/B" -> "ab" (don't let the 'a' get stripped)
    .replace(/&/g, ' and ')
    .replace(/[''`]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter((w) => !STOP.has(w))
    .join('-')
  if (slug.length > 60) {
    slug = slug.slice(0, 60)
    slug = slug.slice(0, slug.lastIndexOf('-') >= 0 ? slug.lastIndexOf('-') : 60)
  }
  return slug
}

// The 10 seed articles already on disk — explicit slugs so they are NOT
// regenerated and are counted in their clusters. Marked published.
const SEEDS = [
  ['improve-conversion-nextjs-landing-page', 'How to Improve Conversion Rate on a Next.js Landing Page', 'framework-fixes'],
  ['fix-low-converting-react-hero-section', "Why Your React Hero Section Isn't Converting (and How to Fix It)", 'framework-fixes'],
  ['measure-scroll-depth-posthog', 'How to Measure Scroll Depth in PostHog', 'posthog-recipes'],
  ['build-signup-funnel-posthog', 'How to Build a Signup Funnel in PostHog for a SaaS Site', 'posthog-recipes'],
  ['track-cta-clicks-posthog', 'How to Track CTA Clicks in PostHog with Autocapture', 'posthog-recipes'],
  ['good-conversion-rate-saas-landing-page', 'What Is a Good Conversion Rate for a SaaS Landing Page?', 'benchmarks'],
  ['average-bounce-rate-developer-tools', 'What Is the Average Bounce Rate for Developer Tools?', 'benchmarks'],
  ['good-trial-to-paid-conversion-rate-saas', "What's a Good Free-Trial-to-Paid Conversion Rate for SaaS?", 'benchmarks'],
  ['what-is-conversion-rate-optimization', 'What Is Conversion Rate Optimization (CRO)?', 'concepts'],
  ['what-is-a-micro-conversion', 'What Is a Micro-Conversion? Examples for SaaS', 'concepts'],
]

// Curated titles per cluster (seeds excluded — they're added from SEEDS).
const TITLES = {
  'framework-fixes': [
    // Next.js
    'How to Improve Conversion on a Next.js Pricing Page',
    'How to Reduce Signup Form Abandonment in Next.js App Router',
    'How to Fix a Hydration-Delayed CTA in Next.js',
    'How to Add an Exit-Intent Popup in Next.js Without Hurting LCP',
    'How to Make a Next.js Server Component Hero Convert Better',
    'How to Lazy-Load Below-the-Fold Sections in Next.js for Conversion',
    'How to A/B Two Hero Variants with Next.js Middleware',
    'How to Use next/font to Stop Layout Shift That Hurts Conversion',
    'How to Add a Sticky Mobile CTA in Next.js App Router',
    'How to Improve the Blog-to-Signup Path in Next.js',
    'How to Fix Slow Route Transitions Hurting Conversion in Next.js',
    'How to Render Social Proof Server-Side in Next.js',
    'How to Gate a Next.js CTA Behind a Fast Server Action',
    'How to Reduce Bounce on a Next.js Marketing Page',
    'How to Personalise a Next.js Hero with Cookies Without a Flash',
    'How to Defer Third-Party Scripts in Next.js to Lift Conversion',
    // React / Vite
    'How to Fix a Below-the-Fold CTA in a React SPA',
    'How to Reduce Form Abandonment in a React Multi-Step Signup',
    'How to Add a Sticky CTA in a React Single-Page App',
    'How to Lazy-Load a Heavy React Hero to Improve Conversion',
    'How to Stop a React Re-Render From Flickering Your CTA',
    'How to Improve Conversion on a React Pricing Toggle',
    'How to Code-Split a React Landing Page for Faster First Paint',
    'How to Show an Exit-Intent Modal in React Without Annoying Users',
    'How to Fix Slow React Hydration That Delays Interaction',
    'How to Build a Trust Bar in React That Converts',
    'How to Defer Analytics in React So the CTA Loads First',
    'How to Improve Mobile Tap Targets in a React Landing Page',
    'How to Inline Critical CSS in a Vite React App for Conversion',
    'How to Measure CTA Visibility in React with IntersectionObserver',
    // Astro
    'How to Improve Conversion on an Astro Landing Page with Islands',
    'How to Use client:visible So an Astro CTA Hydrates Late',
    'How to Optimise the Astro Image Component for a Fast Hero LCP',
    'How to Add an Interactive Pricing Toggle as an Astro Island',
    'How to Reduce JavaScript on an Astro Page to Cut Bounce',
    'How to Add a Sticky CTA Island in Astro',
    'How to Server-Render Social Proof in Astro',
    'How to A/B Test an Astro Page with Edge Middleware',
    'How to Defer a Newsletter Widget as an Astro client:idle Island',
    'How to Fix Cumulative Layout Shift on an Astro Landing Page',
    'How to Improve Conversion on an Astro Content Collection Blog',
    'How to Add an Exit-Intent Island in Astro',
    'How to Inline Critical Styles in Astro for First Paint',
    'How to Turn a Static Astro Hero Into a Persuasive Above-the-Fold',
    // SvelteKit
    'How to Reduce Signup Form Abandonment in SvelteKit',
    'How to Use a SvelteKit Form Action to Cut Checkout Drop-Off',
    'How to Progressive-Enhance a SvelteKit CTA with use:enhance',
    'How to Improve Conversion with a SvelteKit Load Function Prefetch',
    'How to Add a Sticky CTA in SvelteKit Without Layout Shift',
    'How to Optimise SvelteKit Hero Images with enhanced:img',
    'How to A/B Test a Route in SvelteKit with Hooks',
    'How to Show Inline Form Errors in SvelteKit Without a Reload',
    'How to Reduce Bounce on a SvelteKit Marketing Page',
    'How to Defer Analytics in SvelteKit to Load the CTA First',
    'How to Personalise a SvelteKit Page in a Server Load Function',
    'How to Improve Mobile Conversion in a SvelteKit App',
    'How to Add an Exit-Intent Modal in SvelteKit',
    'How to Server-Render Social Proof in SvelteKit',
    // Remix
    'How to Cut Signup Abandonment with a Remix Action and useFetcher',
    'How to Improve Conversion with a Remix Loader Prefetch',
    'How to Progressive-Enhance a Remix Form for Higher Completion',
    'How to Add Inline Validation in a Remix Form Without JS Reloads',
    'How to Add a Sticky CTA in a Remix Route',
    'How to A/B Test a Remix Route in the Loader',
    'How to Reduce Bounce on a Remix Landing Page',
    'How to Optimise LCP on a Remix Marketing Route',
    'How to Personalise a Remix Page from the Loader',
    'How to Defer Non-Critical Data in Remix to Speed the CTA',
    'How to Show Social Proof from a Remix Loader',
    'How to Improve Mobile Conversion in a Remix App',
    // Vue 3
    'How to Improve Conversion on a Vue 3 Landing Page',
    'How to Reduce Form Abandonment in a Vue 3 Signup',
    'How to Add a Sticky CTA in Vue 3 with a Composable',
    'How to Lazy-Load a Vue 3 Hero with defineAsyncComponent',
    'How to Fix Layout Shift in a Vue 3 Landing Page',
    'How to A/B Test a Vue 3 Page with a Feature Flag',
    'How to Show an Exit-Intent Modal in Vue 3',
    'How to Improve Mobile Tap Targets in a Vue 3 App',
    'How to Defer Third-Party Scripts in Vue 3 for Conversion',
    'How to Build a Trust Bar Component in Vue 3',
    // Nuxt 3
    'How to Improve Conversion on a Nuxt 3 Landing Page',
    'How to Reduce Signup Abandonment in a Nuxt 3 Form',
    'How to Use useAsyncData in Nuxt 3 to Prefetch and Speed the CTA',
    'How to Add a Sticky CTA in Nuxt 3 Without Layout Shift',
    'How to Optimise Nuxt Image for a Fast Hero LCP',
    'How to A/B Test a Nuxt 3 Route with Middleware',
    'How to Defer Plugins in Nuxt 3 to Load the CTA First',
    'How to Server-Render Social Proof in Nuxt 3',
    'How to Personalise a Nuxt 3 Page in Server Middleware',
    'How to Fix Cumulative Layout Shift on a Nuxt 3 Page',
    'How to Improve Mobile Conversion in a Nuxt 3 App',
    'How to Add an Exit-Intent Modal in Nuxt 3',
    // Plain HTML
    'How to Improve Conversion on a Plain HTML Landing Page',
    'How to Add a Sticky CTA in Plain HTML and CSS',
    'How to Reduce Form Abandonment in a Plain HTML Signup Form',
    'How to Lazy-Load Images on a Static HTML Page for a Faster LCP',
    'How to Add an Exit-Intent Popup in Vanilla JavaScript',
    'How to Inline Critical CSS in a Static HTML Page',
    'How to Defer Third-Party Scripts on a Static HTML Site',
    'How to Add Native Form Validation in Plain HTML to Cut Abandonment',
    'How to Build a Trust Bar in Plain HTML and CSS',
    'How to Fix Layout Shift on a Static HTML Landing Page',
    // Backfill on the seven ICP frameworks (replaced off-scope Gatsby + SolidJS).
    // Next.js
    'How to Reduce Layout Shift from next/image on a Next.js Hero',
    'How to Prefetch the Signup Route in Next.js to Speed Conversion',
    // React
    'How to Debounce a React Search Box Without Losing Conversions',
    'How to Persist a Half-Filled React Form to Cut Abandonment',
    // Astro
    'How to Add a View Transition to an Astro Page Without Hurting Conversion',
    'How to Use Astro Server Islands for Personalised Social Proof',
    // SvelteKit
    'How to Prefetch on Hover in SvelteKit with data-sveltekit-preload-data',
    'How to Stream a Slow Section in SvelteKit So the CTA Renders First',
    // Remix
    'How to Use a Remix fetcher.Form for an Inline Newsletter Signup',
    'How to Defer Slow Data in Remix with defer and Await',
    // Vue 3
    'How to Use Vue Suspense to Keep the CTA Visible While Data Loads',
    'How to Prefetch a Route on Hover in Vue Router for Faster Conversion',
    // Nuxt 3
    'How to Use Nuxt useLazyAsyncData to Render the CTA Before Data',
    'How to Add a Nuxt Route Middleware Redirect That Preserves Intent',
    // plain HTML
    'How to Preload Your Hero Image in Plain HTML for a Faster LCP',
    'How to Add an Accessible Modal in Plain HTML with the dialog Element',
  ],
  'posthog-recipes': [
    'How to Track a Button Click as a Custom Event in PostHog',
    'How to Create a Conversion Goal in PostHog',
    'How to Measure Time on Page in PostHog',
    'How to Build a Retention Chart in PostHog for a SaaS',
    'How to Use PostHog Paths to See Where Users Go After the Homepage',
    'How to Create a Cohort of High-Intent Visitors in PostHog',
    'How to Find Your Most-Viewed Pages in PostHog with HogQL',
    'How to Track Outbound Link Clicks in PostHog',
    'How to Measure Form Field Drop-Off in PostHog',
    'How to Set Up a Pageview Funnel in PostHog Without Code',
    'How to Calculate Click-Through Rate in PostHog with HogQL',
    'How to Track Pricing Page Visits in PostHog',
    'How to Use PostHog Feature Flags to Gate a New CTA',
    'How to Break Down Scroll Depth by Page in PostHog',
    'How to Find Rage Clicks in PostHog',
    'How to Track Sign-Ups by Traffic Source in PostHog',
    'How to Build a Weekly Active Users Chart in PostHog',
    'How to Measure Bounce Rate in PostHog with HogQL',
    'How to Watch Session Recordings of Users Who Did Not Convert in PostHog',
    'How to Create a Dashboard for Landing Page Performance in PostHog',
    'How to Track a Multi-Step Checkout Funnel in PostHog',
    'How to Segment Conversion by Device in PostHog',
    'How to Use PostHog Surveys to Ask Why Users Did Not Sign Up',
    'How to Find Drop-Off Between Two Events in PostHog',
    'How to Track Video Play Events in PostHog',
    'How to Measure Activation Rate in PostHog with HogQL',
    'How to Compare This Week vs Last Week Conversions in PostHog',
    'How to Track UTM Campaigns in PostHog',
    'How to Identify Your Highest-Converting Referrers in PostHog',
    'How to Set a Conversion Alert in PostHog',
    'How to Use HogQL to Count Unique Visitors Per Day',
    'How to Track a CTA Impression with IntersectionObserver and PostHog',
    'How to Measure Median Session Duration in PostHog with quantile',
    'How to Find Pages With High Exit Rates in PostHog',
    'How to Build a Signup-to-Activation Funnel in PostHog',
    'How to Track Add-to-Cart Events in PostHog',
    'How to Measure Mobile vs Desktop Conversion in PostHog',
    'How to Tag Internal Traffic So It Does Not Skew PostHog Data',
    'How to Use PostHog Group Analytics for B2B Accounts',
    'How to Track Search Queries on Your Site in PostHog',
    'How to Measure the Conversion Impact of a Deploy in PostHog',
    'How to Find Your Top Clicked Elements in PostHog with $autocapture',
    'How to Build a New vs Returning Visitor Breakdown in PostHog',
    'How to Track Pricing Plan Selection in PostHog',
    'How to Measure Email Capture Rate in PostHog',
    'How to Use HogQL to Find Single-Page Sessions',
    'How to Track Onboarding Step Completion in PostHog',
    'How to Measure Trial Starts by Plan in PostHog',
    'How to Build a Funnel With a Conversion Window in PostHog',
    'How to Find Where Mobile Users Drop Off in PostHog',
    'How to Track Scroll-to-Pricing as a Micro-Conversion in PostHog',
    'How to Use PostHog Trends to Spot a Conversion Dip',
    'How to Measure Form Submission Errors in PostHog',
    'How to Segment Conversion by Landing Page in PostHog',
    'How to Track First-Click Attribution in PostHog',
    'How to Use HogQL to Rank Pages by Conversion Rate',
    'How to Measure Repeat-Visit Conversion in PostHog',
    'How to Build a Weekly Conversion-Rate Trend in PostHog',
    'How to Track Demo Requests in PostHog',
    'How to Find the Pages With the Highest Bounce in PostHog',
    'How to Use PostHog Cohorts to Retarget Cart Abandoners',
    'How to Measure Hero CTA vs Footer CTA Clicks in PostHog',
    'How to Track Churn Signals Like Account Deletions in PostHog',
    'How to Build a Daily Signups Chart in PostHog with HogQL',
    'How to Measure Conversion by Browser in PostHog',
    'How to Track Coupon Code Usage in PostHog',
    'How to Find High-Scroll, No-Click Sessions in PostHog',
    'How to Use HogQL countIf for Conditional Conversion Counts',
    'How to Measure the Drop-Off From Pricing to Checkout in PostHog',
    'How to Track Tab Switching on a Pricing Page in PostHog',
    'How to Measure Average Pages Per Session in PostHog',
    'How to Track Newsletter Signups by Source in PostHog',
    'How to Find Your Best-Converting Blog Posts in PostHog',
    'How to Use PostHog to Measure Above-the-Fold CTA Visibility',
    'How to Track Logged-In vs Logged-Out Conversion in PostHog',
    'How to Measure Weekend vs Weekday Conversion in PostHog',
    'How to Use HogQL multiIf to Bucket Visitors by Engagement',
    'How to Track Pricing FAQ Expansions in PostHog',
    'How to Measure the Conversion Rate of a Specific Campaign in PostHog',
    'How to Find Pages Where Users Scroll But Do Not Convert in PostHog',
    'How to Track Free-to-Paid Upgrades in PostHog',
    'How to Build a Funnel Segmented by Country in PostHog',
    'How to Measure CTA Click-Through by Position in PostHog',
    'How to Track Form Start vs Form Submit in PostHog',
    'How to Use HogQL to Compute a 7-Day Rolling Signup Count',
    'How to Measure the Effect of a Pricing Change in PostHog',
  ],
  'benchmarks': [
    'What Is a Good Bounce Rate for a SaaS Marketing Site?',
    'What Is a Good Signup Conversion Rate for a Developer Tool?',
    'What Is a Good Click-Through Rate on a Hero CTA?',
    'What Is a Good Scroll Depth for a Landing Page?',
    'What Is the Average Time on Page for a SaaS Landing Page?',
    'What Is a Good Demo-Request Conversion Rate for B2B SaaS?',
    'What Is a Good Email Capture Rate for a Landing Page?',
    'What Is a Good Activation Rate for a SaaS Product?',
    'What Is the Average Pages Per Session for a SaaS Site?',
    'What Is a Good Pricing Page Conversion Rate?',
    'What Is a Good Free-Trial Signup Rate for B2B SaaS?',
    'What Is a Good Checkout Completion Rate for SaaS?',
    'What Is the Average Conversion Rate for an API Product?',
    'What Is a Good Newsletter Signup Conversion Rate?',
    'What Is a Good Mobile Conversion Rate for SaaS?',
    'What Is the Average Cart Abandonment Rate for SaaS Checkouts?',
    'What Is a Good Day-1 Retention Rate for a SaaS Product?',
    'What Is a Good Day-30 Retention Rate for SaaS?',
    'What Is a Good Onboarding Completion Rate for SaaS?',
    'What Is a Good CTA Click Rate on a Pricing Page?',
    'What Is a Good Visitor-to-Lead Rate for B2B SaaS?',
    'What Is a Good Lead-to-Customer Rate for SaaS?',
    'What Is the Average Bounce Rate for a Documentation Site?',
    'What Is a Good Conversion Rate for an Open-Source Landing Page?',
    'What Is a Good Conversion Rate for an AI Product Landing Page?',
    'What Is a Good Conversion Rate for a Developer SDK Page?',
    'What Is the Average Session Duration for a SaaS Marketing Site?',
    'What Is a Good Signup-to-Activation Rate for SaaS?',
    'What Is a Good Trial-to-Paid Rate Without a Credit Card?',
    'What Is a Good Trial-to-Paid Rate With a Credit Card?',
    'What Is a Good Conversion Rate From Paid Search for SaaS?',
    'What Is a Good Conversion Rate From Organic Search for SaaS?',
    'What Is a Good Conversion Rate From Product Hunt Traffic?',
    'What Is the Average Conversion Rate From Hacker News Traffic?',
    'What Is a Good Blog-to-Signup Conversion Rate?',
    'What Is a Good Conversion Rate for a Webinar Landing Page?',
    'What Is a Good Conversion Rate for a Waitlist Page?',
    'What Is a Good First-Contentful-Paint for a Landing Page?',
    'What Is a Good Form Completion Rate for a Signup Form?',
    'What Is a Good Conversion Rate for a Chrome Extension Page?',
    'What Is a Good Upgrade Rate From Free to Paid in SaaS?',
    'What Is a Good Conversion Rate for a Fintech Landing Page?',
    'What Is the Average Exit Rate for a Pricing Page?',
    'What Is a Good Conversion Rate for a Mobile App Landing Page?',
    'What Is a Good Repeat-Visitor Conversion Rate for SaaS?',
    'What Is a Good Conversion Rate for Cold Paid-Social Traffic?',
    'What Is a Good Add-to-Cart Rate for a SaaS Checkout?',
    'What Is the Average Number of Sessions Before a SaaS Signup?',
    'What Is a Good Conversion Rate for a Developer Newsletter?',
    'What Is a Good Conversion Rate for a Self-Serve SaaS?',
    'What Is a Good Conversion Rate for a Sales-Led SaaS Demo?',
    'What Is a Good Bounce Rate for a Blog?',
    'What Is a Good Conversion Rate for a B2B Lead-Gen Form?',
    'What Is the Average Conversion Rate for Vertical SaaS?',
    'What Is a Good Conversion Rate for a Freemium Developer Tool?',
    'What Is a Good Conversion Rate for Enterprise SaaS?',
    'What Is a Good Homepage-to-Pricing Click Rate for SaaS?',
  ],
  'core-web-vitals': [
    'Does LCP Affect Conversion Rate? What the Evidence Shows',
    'Does Cumulative Layout Shift Hurt Conversion?',
    'Does INP Affect Conversion on a Landing Page?',
    'How to Fix a Slow LCP on a Next.js Landing Page',
    'How to Fix Cumulative Layout Shift in React',
    'How to Improve INP on a React Landing Page',
    'How to Find Your LCP Element with Chrome DevTools',
    'How to Fix LCP Caused by a Hero Image',
    'How to Fix Layout Shift Caused by Web Fonts',
    'How to Fix Layout Shift Caused by Ads or Embeds',
    'How to Reduce TTFB on a Server-Rendered Landing Page',
    'How to Measure Core Web Vitals in the Field with web-vitals.js',
    'How to Improve LCP with Image Preloading',
    'How to Fix INP Caused by Heavy JavaScript on Click',
    'How to Lazy-Load Below-the-Fold Images Without Hurting LCP',
    'What Is a Good LCP Score for a Landing Page?',
    'What Is a Good CLS Score for Conversion?',
    'What Is a Good INP Score in 2026?',
    'How to Fix Render-Blocking CSS That Slows LCP',
    'How to Preconnect to Third-Party Origins to Speed Up LCP',
    'How to Fix Layout Shift From Images Without Dimensions',
    'How to Reduce JavaScript Bundle Size to Improve INP',
    'How to Use fetchpriority=high on Your Hero Image',
    'How to Fix a Slow LCP on a WordPress Landing Page',
    'How to Improve Core Web Vitals on an Astro Site',
    'How to Improve Core Web Vitals in a Vue 3 App',
    'How to Fix LCP Caused by a Slow API Call',
    'How to Measure LCP, CLS, and INP in PostHog',
    'How to Set a Performance Budget That Protects Conversion',
    'How to Fix Layout Shift From a Cookie Consent Banner',
    'How to Defer Non-Critical JavaScript to Improve INP',
    'How to Fix a Slow LCP Caused by a Carousel',
    'How to Improve LCP on a Mobile Landing Page',
    'How to Reduce Main-Thread Work to Improve INP',
    'How Does Page Speed Affect Bounce Rate?',
    'How to Fix Layout Shift From Dynamically Injected Content',
    'How to Self-Host Fonts to Improve LCP and CLS',
    'How to Audit Core Web Vitals with Lighthouse',
    'How to Fix a Slow LCP on a Gatsby Site',
    'How to Improve INP on a Form-Heavy Page',
    'How to Use the Speculation Rules API to Speed Up Navigation',
    'How to Fix Layout Shift From an Image Gallery',
    'How Does LCP Differ on Mobile vs Desktop?',
    'How to Reduce Time to Interactive on a React Landing Page',
    'How to Fix LCP Regressions After a Deploy',
    'How to Prioritise the Hero CTA in the Critical Rendering Path',
    'How to Fix INP on a Pricing Page With Many Toggles',
    'How to Measure Real-User Core Web Vitals by Page',
    'How to Fix a Slow LCP Caused by Client-Side Rendering',
    'How to Cut Layout Shift on a Mobile Signup Form',
  ],
  'concepts': [
    'What Is a Conversion Funnel?',
    'What Is Bounce Rate vs Exit Rate?',
    'What Is a Call to Action (CTA)?',
    'What Is Above the Fold in Web Design?',
    'What Is a Landing Page?',
    'What Is a Value Proposition?',
    'What Is Social Proof in Conversion?',
    'What Is A/B Testing?',
    'What Is Statistical Significance in A/B Testing?',
    'What Is a Conversion Goal?',
    'What Is Activation in SaaS?',
    'What Is Product-Led Growth?',
    'What Is a North Star Metric?',
    'What Is Churn Rate?',
    'What Is Retention Rate?',
    'What Is a Cohort in Analytics?',
    'What Is Customer Acquisition Cost (CAC)?',
    'What Is Lifetime Value (LTV)?',
    'What Is the LTV to CAC Ratio?',
    'What Is a Funnel Drop-Off?',
    'What Is a Heatmap in CRO?',
    'What Is Session Replay?',
    'What Is Scroll Depth?',
    'What Is a Rage Click?',
    'What Is Friction in a Signup Flow?',
    'What Is a Hero Section?',
    'What Is a Sticky CTA?',
    'What Is an Exit-Intent Popup?',
    'What Is Progressive Enhancement?',
    'What Is a Reverse Trial?',
    'What Is Freemium vs Free Trial?',
    'What Is Time to Value?',
    'What Is a Lead Magnet?',
    'What Is a Squeeze Page?',
    'What Is Answer Engine Optimisation (AEO)?',
    'What Is Programmatic SEO?',
    'What Is Click-Through Rate (CTR)?',
    'What Is a Control vs Variant in an Experiment?',
    'What Is a Feature Flag?',
    'What Is Autocapture in Analytics?',
    'What Is a Custom Event in Product Analytics?',
    'What Is a Funnel Conversion Window?',
    'What Is First-Click vs Last-Click Attribution?',
    'What Is a Vanity Metric?',
    'What Is a Qualified Lead?',
    'What Is Onboarding in SaaS?',
    'What Is the Pirate Metrics (AARRR) Framework?',
    'What Is a Bounce in Web Analytics?',
  ],
  'automation': [
    'Can an AI Agent Open Pull Requests on Your Repo? How It Works',
    'How to Automate Conversion Fixes with GitHub Pull Requests',
    'What Is the Approval-Gate Pattern for AI Code Changes?',
    'How to Safely Auto-Roll-Back a Bad Deploy Using Bounce Rate',
    'Should You Let an AI Auto-Merge Code?',
    'How AI Coding Agents Map a Repo Before Making a Change',
    'How to Review an AI-Generated Pull Request Safely',
    'What Guardrails Should an AI Growth Agent Have?',
    'How an AI Agent Picks the Highest-Impact Conversion Fix',
    'How to Connect PostHog to an AI Growth Agent',
    'How an AI Agent Grounds a Fix in Real User Behaviour',
    'Why Ship Conversion Fixes as Code Instead of a Dashboard?',
    'How to Keep an AI Agent From Touching Protected Files',
    'How an AI Agent Writes a Pull Request Description You Can Trust',
    'How to Measure Whether an AI-Shipped Fix Actually Worked',
    'What Is a Receipt-Style Pull Request?',
    'How an AI Agent Detects a Conversion Regression',
    'How to Set Brand Guardrails for an AI Growth Agent',
    'Can an AI Agent Optimise Conversion Without Human Review?',
    'How AI Agents Use a Telegram Approval Flow',
    'How an AI Growth Agent Differs From an A/B Testing Tool',
    'How an AI Agent Reads Scroll Depth and Click Data',
    'How to Roll Back an AI-Merged Pull Request',
    'What Repos Can an AI Growth Agent Work On?',
    'How an AI Agent Discovers Routes in a Next.js App',
    'How an AI Agent Avoids Breaking Your Build',
    'How to Trust an AI Agent With Repo Access',
    'How an AI Agent Prioritises the Funnel Over the Homepage',
    'Why Weekly Cadence Beats One-Off CRO Audits',
    'How an AI Agent Handles a Monorepo',
    'How to Give an AI Agent Just Enough GitHub Permission',
    'How an AI Agent Uses a Vercel Preview to Validate a Fix',
    'What Happens When an AI Agent Finds No Worthwhile Fix?',
    'How an AI Agent Tracks Competitor Landing Pages',
    'How to Audit Every Change an AI Agent Has Made',
    'How an AI Agent Decides Between Copy and Layout Fixes',
    'Can an AI Agent Improve Conversion on a Static Site?',
    'How an AI Agent Learns From a Rejected Pull Request',
    'How an AI Agent Respects Your Design System',
    'How to Start With an AI Growth Agent in Under an Hour',
  ],
  'experimentation': [
    'How to A/B Test a Landing Page Without a Testing Platform',
    'Is My A/B Test Result Statistically Significant?',
    'How Many Visitors Do You Need for an A/B Test?',
    'How to Calculate Sample Size for an A/B Test',
    'How to A/B Test a CTA Button Without Flicker',
    'How to Run an A/B Test with PostHog Feature Flags',
    'How Long Should You Run an A/B Test?',
    'What Is a Minimum Detectable Effect in A/B Testing?',
    'How to Avoid Peeking in an A/B Test',
    'How to A/B Test a Headline on a Landing Page',
    'How to A/B Test Pricing Without Hurting Trust',
    'What Is a False Positive in A/B Testing?',
    'How to Interpret a P-Value in an A/B Test',
    'How to A/B Test a Signup Flow',
    'How to Split Traffic 50/50 for an A/B Test',
    'How to A/B Test on Low Traffic',
    'What Is Bayesian vs Frequentist A/B Testing?',
    'How to A/B Test a Server-Rendered Page Without Layout Shift',
    'How to Measure the Conversion Lift From an A/B Test',
    'How to A/B Test a Mobile CTA',
    'How to Set Up an A/B Test in Next.js with Middleware',
    'How to Run a Holdout Group for a Conversion Change',
    'How to A/B Test an Email Capture Form',
    'What Is Multivariate Testing and When to Use It?',
    'How to Avoid Sample Ratio Mismatch in an A/B Test',
    'How to A/B Test a Pricing Page Layout',
    'How to Decide a Winner Without a Significance Calculator',
    'How to A/B Test Social Proof Placement',
    'How to A/B Test a Hero Image vs a Product Demo',
    'How to Run Sequential A/B Tests Safely',
    'How to A/B Test a Free Trial Length',
    'What Is the Novelty Effect in A/B Testing?',
    'How to A/B Test a CTA Microcopy Change',
    'How to Calculate a Conversion Rate Confidence Interval',
    'How to A/B Test Without Slowing Down Your Page',
    'How to Prioritise Which A/B Test to Run First',
    'How to A/B Test an Onboarding Step',
    'How to Run a Conversion Experiment With a Feature Flag in React',
    'How to Avoid Common A/B Testing Mistakes',
    'When Is an A/B Test Not Worth Running?',
  ],
  'comparisons': [
    'PostHog vs Google Analytics 4 for Conversion Tracking',
    'CRO Agency vs AI Growth Agent for a Solo Founder',
    'A/B Testing Tools vs Shipping the Fix',
    'PostHog vs Mixpanel for Product Analytics',
    'PostHog vs Amplitude for SaaS',
    'Hotjar vs PostHog for Heatmaps and Session Replay',
    'Optimizely vs PostHog Feature Flags',
    'VWO vs PostHog for A/B Testing',
    'Google Optimize Alternatives After Its Shutdown',
    'Plausible vs PostHog for Privacy-Friendly Analytics',
    'Vercel Analytics vs PostHog for Conversion',
    'Next.js vs Astro for a High-Converting Landing Page',
    'SvelteKit vs Next.js for Marketing Sites',
    'Server Components vs Client Components for Conversion',
    'Static Site vs SSR for Landing Page Conversion',
    'Unbounce vs a Coded Landing Page',
    'Webflow vs Next.js for a SaaS Landing Page',
    'Framer vs Coded Landing Pages for Conversion',
    'Heatmaps vs Funnels for Finding Conversion Problems',
    'Session Replay vs Analytics for Diagnosing Drop-Off',
    'Email Capture vs Free Trial as a First Conversion',
    'Credit-Card-Required vs No-Card Free Trials',
    'Freemium vs Free Trial for Developer Tools',
    'Demo-Led vs Self-Serve Conversion for B2B SaaS',
    'Single CTA vs Multiple CTAs on a Landing Page',
    'Long-Form vs Short-Form Landing Pages',
    'Live Chat vs a Better FAQ for Conversion',
    'Popup vs Inline Email Capture',
    'Carousel vs Static Hero for Conversion',
    'Video vs Screenshot in a SaaS Hero',
    'Manual CRO vs Automated Conversion Fixes',
    'PostHog Cloud vs Self-Hosted for a Small Team',
    'GA4 vs Plausible for Marketing Attribution',
    'Pricing Table vs Pricing Calculator for Conversion',
    'Annual vs Monthly Pricing Default for Conversion',
    'Sticky CTA vs Repeated Inline CTAs',
    'Dark Mode vs Light Mode Landing Pages for Conversion',
    'Headless CMS vs Hardcoded Copy for a Landing Page',
    'Tailwind vs Plain CSS for a Fast Landing Page',
    'PostHog Funnels vs HogQL for Custom Conversion Analysis',
  ],
  'patterns': [
    'The Anatomy of a High-Converting SaaS Hero Section',
    'Pricing Page Layouts That Convert for Developer Tools',
    'How Many CTAs Should a Landing Page Have?',
    'Where to Put Social Proof on a Landing Page',
    'The Best Above-the-Fold Layout for a SaaS Landing Page',
    'How to Structure a Feature Section That Converts',
    'The Ideal Length of a SaaS Landing Page',
    'How to Design a Pricing Toggle That Does Not Confuse Users',
    'The Best Place for a Demo Video on a Landing Page',
    'How to Write a Hero Headline That Converts',
    'How to Design a Trust Bar of Customer Logos',
    'The Best CTA Microcopy for a Free Trial',
    'How to Lay Out a Comparison Table That Converts',
    'How to Design an FAQ Section That Removes Objections',
    'The Best Newsletter Signup Placement on a Blog',
    'How to Design a Sticky Header CTA',
    'How to Structure a Testimonial Section for Trust',
    'The Best Mobile Landing Page Layout for Conversion',
    'How to Design a Two-Step Signup That Converts',
    'How to Use Whitespace to Direct Attention to the CTA',
    'The Best Form Length for a Signup Page',
    'How to Design a Pricing Page With Three Tiers',
    'How to Add Urgency Without Dark Patterns',
    'The Best Way to Show a Free Trial Offer',
    'How to Design a Footer That Recovers Lost Visitors',
    'How to Structure a Case Study Page That Converts',
    'The Best Hero Layout for an API Product',
    'How to Design a Cookie Banner That Does Not Kill Conversion',
    'How to Lay Out a Developer-Focused Landing Page',
    'How to Design an Onboarding Checklist That Drives Activation',
  ],
  'playbooks': [
    'How to Get Your First 100 SaaS Signups as a Solo Founder',
    'Conversion Optimisation for Founders Who Cannot Afford an Agency',
    'How to Find Your Biggest Conversion Leak in an Afternoon',
    'A One-Week Conversion Audit You Can Run Yourself',
    'How to Launch on Product Hunt Without Wasting the Traffic',
    'How to Turn Blog Readers Into Signups',
    'How to Run Your First Five User Interviews for Conversion',
    'How to Price Your SaaS for Your First Customers',
    'How to Set Up Analytics as a Non-Technical Founder',
    'How to Write Landing Page Copy When You Are Not a Copywriter',
    'How to Get Feedback on Your Landing Page Before Launch',
    'How to Prioritise Conversion Fixes With No Data Team',
    'How to Build a Weekly Conversion Habit as a Solo Founder',
    'How to Convert Free Users to Paid Without a Sales Team',
    'How to Recover Abandoned Signups With a Simple Email',
    'How to Validate a Landing Page Before You Build the Product',
    'How to Use a Waitlist to Drive Early Conversions',
    'How to Reduce Churn in Your First Year of SaaS',
    'How to Find Conversion Wins in Your Existing Analytics',
    'How to Ship a Conversion Fix Every Week Without a Big Team',
  ],
}

// ── assemble + validate ───────────────────────────────────────────────────────
const topics = []
const bySlug = new Map()
const issues = []

function add(slug, title, cluster, status) {
  if (!CLUSTER_SLUGS.includes(cluster)) issues.push(`unknown cluster "${cluster}" for "${title}"`)
  if (slug.length > 60) issues.push(`slug >60 chars (${slug.length}): ${slug}`)
  if (bySlug.has(slug)) issues.push(`duplicate slug "${slug}" — "${title}" vs "${bySlug.get(slug)}"`)
  bySlug.set(slug, title)
  topics.push({ slug, title, cluster, status })
}

for (const [slug, title, cluster] of SEEDS) add(slug, title, cluster, 'published')
for (const cluster of Object.keys(TITLES)) {
  for (const title of TITLES[cluster]) add(slugify(title), title, cluster, 'draft')
}

if (issues.length) {
  console.error('build-topics: validation FAILED:')
  for (const i of [...new Set(issues)]) console.error('  ' + i)
  process.exit(1)
}

// counts per cluster
const counts = {}
for (const t of topics) counts[t.cluster] = (counts[t.cluster] || 0) + 1

writeFileSync(OUT, JSON.stringify(topics, null, 2) + '\n', 'utf8')
console.log(`build-topics: wrote ${topics.length} topics → content/blog-topics.json`)
console.log('per cluster:')
for (const c of CLUSTER_SLUGS) console.log(`  ${String(counts[c] || 0).padStart(3)}  ${c}`)
